accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views    

urlpatterns = [
    # Login / Log Out
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='accounts/login.html'),
         name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='accounts/logout.html'),
         name='logout'),

    # Sign Up
    path('accounts/signup', views.sign_up, name="signup"),

    path('user/<int:pk>/update', views.user_update, name='user_update'),
]

heal/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.insuranceproducts_view, name='insuranceproducts_view'),
    path('users/', views.users_view, name='users_view'),
    path('accounts/', views.accounts_view, name='accounts_view'),
    path('recives/', views.recives_view, name='recives_view'),
    
    path('user/<int:pk>', views.user_detail, name='user_detail'),
    path('account/<int:pk>', views.account_detail, name='account_detail'),
    path('product/<int:pk>', views.product_detail, name='product_detail'),
    path('recive/<int:pk>', views.recive_detail, name='recive_detail'),

    path('product/<int:product_id>/buy', views.product_buy, name='product_buy'),
    path('account/new', views.account_create, name='account_form'),
    
    path('account/<int:pk>/update', views.account_update, name='account_update'),
    path('recive/<int:pk>/update', views.recive_update, name='recive_update'),
    path('user/<int:pk>/update', views.user_update, name='user_update'),

   path('account/<int:pk>/delete', views.account_delete, name='account_delete'),
   path('recive/<int:pk>/delete', views.recive_delete, name='recive_delete'), 



]   

heal_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('heal.urls')),
    path('auth/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.core.validators import RegexValidator
# Create your models here.
class CustomUserManager(BaseUserManager):
    def create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user
    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser has to have is_staff being True")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser has to have is_superuser being True")
        return self.create_user(email=email, password=password, **extra_fields)
class User(AbstractUser):
    username = models.CharField(max_length=100, unique=True)
    email = models.CharField(max_length=100, unique=True)
    password = models.CharField(max_length=100 , null=True)
    first_name = models.CharField(verbose_name='First Name', max_length=200,       null=True)
    last_name = models.CharField(verbose_name='Last Name', max_length=200,        null=True)
    gender = models.BooleanField(null=True)
    date_of_birth = models.DateField(null=True)
    user_Identity = models.BigIntegerField(validators=[RegexValidator(r'^\d{13}$', 'Enter a valid 13 digit account number.')] ,null=True)
    
    object =CustomUserManager()
    # USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['username']
    def __str__(self):
        return self.username

heal/models.py
from datetime import datetime
import uuid
from django.utils import timezone
from django.db import models
from django.core.validators import RegexValidator
from accounts.models import User

# Create your models here.

# Create class users

# class Users(models.Model):
#     name = models.CharField(max_length=200)
#     email = models.CharField(max_length=200)
#     password = models.CharField(max_length=200)
#     user_first_name = models.CharField(max_length=200,default='unknown')
#     user_last_name = models.CharField(max_length=200,default='unknown')
#     user_Identity = models.BigIntegerField(validators=[RegexValidator(r'^\d{14}$', 'Enter a valid 14 digit account number.')])

#Create class Accounts

class Accounts(models.Model):
    account_name = models.CharField(max_length=200)
    user_name = models.ForeignKey(User, on_delete=models.CASCADE, related_name = "accounts")
    account_number = models.BigIntegerField(validators=[RegexValidator(r'^\d{10}$', 'Enter a valid 10 digit account number.')])
    balance = models.DecimalField(max_digits=15, decimal_places=2)
    def __str__(self):
        return self.account_name

#Create class InsuranceProducts
class InsuranceProducts(models.Model):
    product_name = models.CharField(max_length=200,default='unknown')
    price = models.DecimalField(max_digits=10, decimal_places=2)
    coverage = models.CharField(max_length=200)
    photo_url = models.TextField(default='unknown')
    def __str__(self):
        return self.product_name
#Create class Recives
class Recives(models.Model):
    created_at = models.DateTimeField(default=timezone.now)
    recive_number = models.CharField(max_length=36, default=uuid.uuid4, editable=False)
    account = models.ForeignKey(Accounts, on_delete=models.CASCADE ,related_name="recives_accout")
    insurance_product = models.ForeignKey(InsuranceProducts, on_delete=models.CASCADE ,related_name="recive_insure")
    recive_date = models.DateTimeField(default=datetime.now)
    recive_amount = models.DecimalField(max_digits=10, decimal_places=2)

heal/forms.py
from django import forms
from .models import Accounts, Recives


# Create new Account
class AccountForm(forms.ModelForm):
    class Meta:
        model = Accounts
        fields = ('account_name', 'account_number', 'balance')

# Create new Recive
class ReciveForm(forms.ModelForm):
    class Meta:
        model = Recives
        fields = ('account', 'insurance_product', 'recive_amount')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from .form import UserForm
from .models import User


# Create your views here.

def sign_up(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('/')
    else:
        form = UserForm()
    return render(request, 'accounts/signup.html', {'form': form})

# Edit User
def user_update(request, pk):
    user = User.objects.get(id=pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect('/', pk=user.pk)
    else:
        form = UserForm(instance=user)
    return render(request, 'heal/user_form.html', {'form': form})

heal/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Accounts, InsuranceProducts, Recives
from accounts.models import User
from .forms import AccountForm, ReciveForm
from accounts.form import UserForm


# Create your views here.

# Show all User data
def users_view(request):
    # users = Users.objects.all()
    # context = {'users': users}
    # return render(request, 'heal/users_view.html', context)
    # /////////////
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'heal/users_view.html', context)

# Show all Accounts data

def accounts_view(request):
    accounts = Accounts.objects.all()
    context = {'accounts': accounts}
    return render(request, 'heal/accounts.html', context)

# Show all insuranceproducts data
def insuranceproducts_view(request):
    insuranceproducts = InsuranceProducts.objects.all()
    context = {'insuranceproducts': insuranceproducts}
    return render(request, 'heal/products.html', context)

# Show all Recives data

def recives_view(request):
    recives = Recives.objects.all()
    context = {'recives': recives}
    return render(request, 'heal/recives.html', context)


# Show a User detail

def user_detail(request, pk):
    user = User.objects.get(id=pk)
    return render(request, 'heal/user_detail.html', {'user':user})

# Show a Account detail

def account_detail(request, pk):
    account = Accounts.objects.all()
    return render(request, 'heal/account_detail.html', {'account':account})

# Show a product detail

def product_detail(request, pk):
    product = InsuranceProducts.objects.get(id=pk)
    return render(request, 'heal/product_detail.html', {'product': product})

# Show a recive detail

def recive_detail(request, pk):
    recive = Recives.objects.get(id=pk)
    return render(request, 'heal/recive_detail.html', {'recive':recive })


# Create Account
def account_create(request):
    if request.method == 'POST':
        form = AccountForm(request.POST)
        if form.is_valid():
            account = form.save()
            return redirect('/')
    else:
        form = AccountForm()
    return render(request, 'heal/account_form.html', {'form': form})

#Create recive
def product_buy(request, product_id):
    if request.method == 'POST':
        form = ReciveForm(request.POST)
        if form.is_valid():
            recive = form.save(commit=False)
            recive.insurance_product_id = product_id
            recive.save()
            return redirect('/')
    else:
        form = ReciveForm()
    return render(request, 'heal/recive_form.html', {'form': form})

# Edit Account 

def account_update(request, pk ):
    account = Accounts.objects.get(id=pk)
    if request.method == "POST":
        form = AccountForm(request.PUT, instance=account)
        if form.is_valid():
            account = form.save()
            return redirect('accounts_view', pk =account.pk)
        else:
            form = AccountForm(instance=account)
        return render(request, 'heal/account_form.html', {'form':form})

# Edit Recive

def recive_update(request, pk ):
    recive = Recives.objects.get(id=pk)
    if request.method == "POST":
        form = ReciveForm(request.POST, instance=recive)
        if form.is_valid():
            recive = form.save()
            return redirect('/', pk =recive.pk)
        else:
            form = ReciveForm(instance=recive)
        return render(request, 'heal/recive_form.html', {'form':form})

# Edit User
def user_update(request, pk):
    user = User.objects.get(id=pk)
    if request.method == "POST":
        form = UserForm(request.POST, instance=user)
        if form.is_valid():
            user = form.save()
            return redirect('/', pk=user.pk)
    else:
        form = UserForm(instance=user)
    return render(request, 'heal/user_form.html', {'form': form})





# Deleate Account

def account_delete(request, pk):
    Accounts.objects.get(id=pk).delete()
    return redirect('/')

# Deleate Recive

def recive_delete(request, pk):
    Recives.objects.get(id=pk).delete()
    return redirect('/')

heal/templates/heal/account_detail.html
{% extends 'heal/base.html' %} 

{% block content %}

<h2 class= "account-detail" >{{account.account_name}}</h2>
<h4 class= "account-detail" >Account Number: {{account.account_number}}</h4>
<h4 class= "account-detail" >Balance: {{account.balance}}</h4>
<h4 class= "account-detail" >User Name: {{account.user_name}}</h4>


{% endblock %}

heal/templates/heal/account_form.html
{% extends 'heal/base.html' %} 

{% block content %}

  <h2 class="account-form">Create a new account</h2>
  <form class="account-form"  method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create account">
  </form>

{% endblock %}

heal/templates/heal/accounts.html
{% extends 'heal/base.html' %} 

{% block content %}

<h2 class ="accounts">Account <a href="">(+)</a></h2>
<ul class ="accounts" >
  {% for account in accounts %}
  <li class ="accounts" >
    <a class ="accounts" href="{% url 'account_detail' pk=account.pk %}">
      {{ account.account_name}}, 
      {{ account.user_name }}
    </a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

heal/templates/heal/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Heal{% endblock %}</title>
  <link rel="stylesheet" type="text/css" href="{% static 'css/heal.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'css/account.css' %}">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/css/foundation.min.css" integrity="sha384-AA7Y5IAEb5v5v5q5q3q5q5i5jK2QxhO5b1R0R48Ug+WQeN6UiLHU0X9nAK/xUPCA" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/foundation-sites@6.6.3/dist/js/foundation.min.js" integrity="sha384-S7YB+cKjd0GKiHWO4hL6U9i0GOM+/PdzglwD/I1/zM1/QQcT/n/nUPrB9k9P6UvA" crossorigin="anonymous"></script>
</head>
<body>
  <header>
    <nav >
      <div class="nav-content">
        <a id="home-nav" href="{% url 'insuranceproducts_view' %}">Home</a>
      </div>
      <div  class="dropdown">
        User
        <div  class="dropdown-content">
          {% if user.is_authenticated %} Welcome
          <br />
          <a href="{% url 'user_detail' pk=user.pk %}">{{ user.username }}</a>
          <br />
          <a href="{% url 'logout' %}">Log out</a>
          {% else %}
          <a href="{% url 'login' %}">Login</a>
          <a href="{% url 'signup' %}">Signup</a>
        </div>
        {% endif %}
      </div>
    </nav>
  </header>
  <main>
    {% block content %}{% endblock %}
  </main>
  <footer>
    <p>Copyright © {{ year }}</p>
  </footer>

  <script>
    $(document).foundation();
  </script>
</body>
</html>

heal/templates/heal/product_detail.html
{% extends 'heal/base.html' %} 

{% block content %}

<h1>Product detail</h1>
{% comment %} <img id="product-detail-header" src="{{ product.photo_url }}" alt="{{ product.product_name }}" /> {% endcomment %}
<p class="product-detail">Product name: {{ product.product_name }}</p>
<p class="product-detail">Product Detail: {{ product.coverage }}</p>
<p class="product-detail">Price: {{ product.price }} Bath</p>
{% if user.is_authenticated %}
<p class="product-detail">
  <a href="{% url 'product_buy' product_id=product.pk %}">Buy</a>
</p>
{% else %}
<p class="product-detail">Please log in to buy the product
  <a href="{% url 'login' %}">Login</a>
</p>
{% endif %}
{% endblock %}

heal/templates/heal/products.html
{% extends 'heal/base.html' %}

{% block content %}

<h1 class="product">Product </h1>

<ul class="product">
  {% for insuranceproduct in insuranceproducts %}
  <li class="product">
    <a href="{% url 'product_detail' pk=insuranceproduct.pk %}">
    <div class="product-photo">
      <img src="{{ insuranceproduct.photo_url }}" alt="" class="product"/>
    </div>
    {{ insuranceproduct.product_name }}</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

heal/templates/heal/recive_form.html
{% extends 'heal/base.html' %}

{% block content %}

  <h1>Buy a product</h1>
  <form class="recive-form" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="recive-form" type="submit" value="Submit" onclick="alert('Thankyou for your purchases' )">
  </form>

  {% endblock %}

heal/templates/heal/recives.html
{% extends 'heal/base.html' %}

{% block content %}

<h2 class="recive">Recives <a class="recive" href="">(+)</a></h2>
<ul class="recive">
  {% for recive in recives %}
  <li class="recive">
    {{ recive.recive_number }}
  </li>
  {% endfor %}
</ul>

{% endblock %}

heal/templates/heal/user_detail.html
{% extends 'heal/base.html' %}

{% block content %}

<h4 class= "user-detail">{{ user.name }} <a  class= "user-detail" href="{% url 'user_update' pk=user.pk %}" >(edit)</a></h4>
<h4 class= "user-detail">Email: {{ user.email }}</h4>
<h4 class= "user-detail">First Name: {{ user.first_name }}</h4>
<h4 class= "user-detail">Last Name: {{ user.last_name }}</h4>
<h4 class= "user-detail"class= "user-detail" >Identity: {{ user.user_Identity }}</h4>

<h4 class= "user-detail" >Accounts</h4>
<ul class= "user-detail" >

  <a href="{% url 'account_form' %}">Add Account</a>
  {% for account in user.accounts_set.all %}
  <li class= "user-detail">
    <a class= "user-detail" href="{% url 'account_detail' pk=account.pk %}">{{ account.account_name}}, {{ account.account_number}}</a>
    <a class= "user-detail" href="{% url 'account_delete' pk=account.pk %}">DELETE</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}

heal/templates/heal/user_form.html
{% extends "heal/base.html" %} {% block content %}

<form class="user-form" method="post">
  {% csrf_token %} {{form.as_p}}

  <input class="user-form-button" type="submit" value="confirm" />
  <input class="user-form" type="hidden" name="next" value="{{ next }}" />
</form>

{% endblock %}

heal/templates/heal/users_view.html
{% extends 'heal/base.html' %}

{% block content %}

<h2 class"users" >User <a href="">(+)</a></h2>
<ul class"users">
  {% for user in users %}
  <li class"users" >
    <a href="{% url 'user_detail' pk=user.pk %}">{{ user.username }}</a>
  </li>
  {% endfor %}
</ul>

{% endblock %}